# Generated by Django 5.1.1 on 2024-10-02 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(max_length=100)),
                ('app_link', models.CharField(max_length=200)),
                ('app_category', models.CharField(choices=[('SN', 'Social Networking'), ('ENT', 'Entertainment'), ('PROD', 'Productivity'), ('GAME', 'Games'), ('HF', 'Health & Fitness'), ('EDU', 'Education'), ('LIFE', 'Lifestyle'), ('FIN', 'Finance'), ('TRV', 'Travel'), ('SHOP', 'Shopping'), ('FD', 'Food & Drink'), ('MA', 'Music & Audio'), ('PV', 'Photo & Video'), ('NM', 'News & Magazines'), ('BUS', 'Business'), ('COM', 'Communication'), ('BR', 'Books & Reference'), ('MN', 'Maps & Navigation'), ('WE', 'Weather'), ('MED', 'Medical'), ('SP', 'Sports'), ('TU', 'Tools & Utilities'), ('DAT', 'Dating'), ('PAR', 'Parenting'), ('BEA', 'Beauty'), ('AD', 'Art & Design'), ('HH', 'House & Home'), ('EVT', 'Events'), ('AV', 'Auto & Vehicles'), ('PER', 'Personalization'), ('COMIC', 'Comics')], max_length=30)),
                ('app_subcategories', models.CharField(choices=[('ACT', 'Action'), ('ADV', 'Adventure'), ('PUZ', 'Puzzle'), ('STR', 'Strategy'), ('ARC', 'Arcade'), ('SIM', 'Simulation'), ('SPR', 'Sports'), ('RPG', 'Role Playing'), ('WKT', 'Workout'), ('MED', 'Meditation'), ('NUT', 'Nutrition'), ('YOG', 'Yoga'), ('RUN', 'Running'), ('CYC', 'Cycling'), ('LAN', 'Language Learning'), ('KID', 'Kids'), ('CRS', 'Courses'), ('STT', 'Study Tools'), ('MTH', 'Math'), ('SCI', 'Science'), ('MUS', 'Music Streaming'), ('POD', 'Podcasts'), ('PLY', 'Music Player'), ('AUD', 'Audio Books'), ('PED', 'Photo Editing'), ('VED', 'Video Editing'), ('CAM', 'Camera'), ('GIF', 'GIF Makers'), ('PFI', 'Personal Finance'), ('INV', 'Investing'), ('BAN', 'Banking'), ('CRY', 'Cryptocurrency'), ('SHO', 'Shopping'), ('FDK', 'Food & Drink'), ('DAT', 'Dating'), ('BEA', 'Beauty'), ('HOM', 'Home Decor'), ('TCB', 'Team Collaboration'), ('CRM', 'CRM'), ('ACC', 'Accounting'), ('PMT', 'Project Management'), ('IMN', 'Inventory Management'), ('MAP', 'Maps'), ('TRA', 'Transportation'), ('HOT', 'Hotels'), ('FLI', 'Flights'), ('LEX', 'Local Experiences'), ('LVS', 'Live Scores'), ('NEW', 'News'), ('FAN', 'Fantasy Sports'), ('SPS', 'Sports Streaming')], max_length=30)),
                ('app_points', models.IntegerField()),
            ],
        ),
    ]
