# Generated by Django 5.1.1 on 2024-10-02 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0002_application_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='app_category',
            field=models.CharField(choices=[('AC', 'App Category'), ('SN', 'Social Networking'), ('ENT', 'Entertainment'), ('PROD', 'Productivity'), ('GAME', 'Games'), ('HF', 'Health & Fitness'), ('EDU', 'Education'), ('LIFE', 'Lifestyle'), ('FIN', 'Finance'), ('TRV', 'Travel'), ('SHOP', 'Shopping'), ('FD', 'Food & Drink'), ('MA', 'Music & Audio'), ('PV', 'Photo & Video'), ('NM', 'News & Magazines'), ('BUS', 'Business'), ('COM', 'Communication'), ('BR', 'Books & Reference'), ('MN', 'Maps & Navigation'), ('WE', 'Weather'), ('MED', 'Medical'), ('SP', 'Sports'), ('TU', 'Tools & Utilities'), ('DAT', 'Dating'), ('PAR', 'Parenting'), ('BEA', 'Beauty'), ('AD', 'Art & Design'), ('HH', 'House & Home'), ('EVT', 'Events'), ('AV', 'Auto & Vehicles'), ('PER', 'Personalization'), ('COMIC', 'Comics')], default='AC', max_length=30),
        ),
        migrations.AlterField(
            model_name='application',
            name='app_subcategories',
            field=models.CharField(choices=[('ASC', 'App  Sub Category'), ('ACT', 'Action'), ('ADV', 'Adventure'), ('PUZ', 'Puzzle'), ('STR', 'Strategy'), ('ARC', 'Arcade'), ('SIM', 'Simulation'), ('SPR', 'Sports'), ('RPG', 'Role Playing'), ('WKT', 'Workout'), ('MED', 'Meditation'), ('NUT', 'Nutrition'), ('YOG', 'Yoga'), ('RUN', 'Running'), ('CYC', 'Cycling'), ('LAN', 'Language Learning'), ('KID', 'Kids'), ('CRS', 'Courses'), ('STT', 'Study Tools'), ('MTH', 'Math'), ('SCI', 'Science'), ('MUS', 'Music Streaming'), ('POD', 'Podcasts'), ('PLY', 'Music Player'), ('AUD', 'Audio Books'), ('PED', 'Photo Editing'), ('VED', 'Video Editing'), ('CAM', 'Camera'), ('GIF', 'GIF Makers'), ('PFI', 'Personal Finance'), ('INV', 'Investing'), ('BAN', 'Banking'), ('CRY', 'Cryptocurrency'), ('SHO', 'Shopping'), ('FDK', 'Food & Drink'), ('DAT', 'Dating'), ('BEA', 'Beauty'), ('HOM', 'Home Decor'), ('TCB', 'Team Collaboration'), ('CRM', 'CRM'), ('ACC', 'Accounting'), ('PMT', 'Project Management'), ('IMN', 'Inventory Management'), ('MAP', 'Maps'), ('TRA', 'Transportation'), ('HOT', 'Hotels'), ('FLI', 'Flights'), ('LEX', 'Local Experiences'), ('LVS', 'Live Scores'), ('NEW', 'News'), ('FAN', 'Fantasy Sports'), ('SPS', 'Sports Streaming')], default='ASC', max_length=30),
        ),
    ]
