# Generated by Django 5.1.1 on 2024-10-02 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0003_alter_application_app_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='app_slug',
            field=models.CharField(default='app-name', max_length=300),
            preserve_default=False,
        ),
    ]
