# Generated by Django 5.1.1 on 2024-10-02 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0004_application_app_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='app_logo',
            field=models.ImageField(blank=True, null=True, upload_to='app_logos/'),
        ),
    ]
