# Generated by Django 5.1.1 on 2024-10-02 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0006_alter_application_app_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='app_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
